#!/usr/bin/env python3
"""
Extract _("...") strings for translation and convert to Qt6 stringdefs so that
they can be picked up by Qt Linguist.
"""
from subprocess import Popen, PIPE
import glob
import operator
import os
import sys

OUT_CPP = "src/qt/cryptonitestrings.cpp"
EMPTY = ['""']


def parse_po(text):
    """
    Parse 'po' format produced by xgettext.
    Return a list of (msgid, msgstr) tuples.
    """
    messages = []
    msgid = []
    msgstr = []
    in_msgid = False
    in_msgstr = False

    for line in text.split('\n'):
        line = line.rstrip('\r')
        if line.startswith('msgid '):
            if in_msgstr:
                messages.append((msgid, msgstr))
                in_msgstr = False
            in_msgid = True
            msgid = [line[6:]]
        elif line.startswith('msgstr '):
            in_msgid = False
            in_msgstr = True
            msgstr = [line[7:]]
        elif line.startswith('"'):
            if in_msgid:
                msgid.append(line)
            if in_msgstr:
                msgstr.append(line)

    if in_msgstr:
        messages.append((msgid, msgstr))

    return messages


def main():
    sources = glob.glob('src/*.cpp') + glob.glob('src/*.h')
    if not sources:
        sys.stderr.write("extract_strings_qt.py: no source files matched src/*.cpp or src/*.h\n")
        return 1

    xgettext = os.getenv('XGETTEXT', 'xgettext')
    child = Popen([xgettext, '--output=-', '-n', '--keyword=_'] + sources, stdout=PIPE)
    (out, _err) = child.communicate()
    if isinstance(out, bytes):
        out = out.decode('utf-8', errors='replace')

    messages = parse_po(out)

    with open(OUT_CPP, 'w', encoding='utf-8') as fh:
        fh.write("""
#include <QtGlobal>

// Automatically generated by extract_strings_qt.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
""")
        fh.write('static const char UNUSED *cryptonite_strings[] = {\n')
        messages.sort(key=operator.itemgetter(0))
        for (msgid, _msgstr) in messages:
            if msgid != EMPTY:
                fh.write('QT_TRANSLATE_NOOP("cryptonite-core", %s),\n' % '\n'.join(msgid))
        fh.write('};\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())